import "oaidl.idl";
import "ocidl.idl";

[
	uuid(F3C40F9C-97DE-4B31-9C81-8C5E9C1F78DD),
	dual,
	oleautomation
]
interface INupicBridge : IDispatch {
	HRESULT init([in] BSTR predictedField, [in] int stepsAhead);
	HRESULT create_model([in] BSTR modelParamsDir);
	HRESULT load_model([in] BSTR modelSaveDir);
	HRESULT save_model([in] BSTR modelSaveDir);
	HRESULT step(
		[in] BSTR timestampStr,
		[in] SAFEARRAY(BSTR) names,
		[in] SAFEARRAY(double) values,
		[out, retval] VARIANT *presult);
	//HRESULT reset();
	HRESULT test(); 
}

[
	uuid(E7E98012-50CB-4F82-B923-422A9C3EE62B)
]
library NupicBridgeTypeLib
{
	importlib("stdole2.tlb");

	[uuid(3894DAC0-35C3-4BCD-9CAB-76B2CFCD0B67)]
	coclass NupicBridge {
		[default] interface INupicBridge;
	};
};